steps:
  - id: zip-dag
    dir: airflow/dags
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        zip -r morning_ai_bot *
  - id: upload
    dir: airflow/dags
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -c
      - |
        ls

